### ISSUE TITLE
DF Chat Enhancements compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [hktrpg/foundryVTT-speak-as#1]
When used with DF Chat Enhancements, the Speak As... module does not show the drop down menu, but rather duplicates the DF Chat Enhancements buttons in a non-functional way. Is there any way to make these two modules play nice?

**Comment by zeteticl** [comment]
@ravingdragoon  
Thankyou for report!
The problem happen because DF chat find the target by class style.

I have create a pull request to DF , So wait to see.
https://github.com/flamewave000/dragonflagon-fvtt/pull/180

**Comment by zeteticl** [comment]
![image](https://user-images.githubusercontent.com/23254376/131958113-e05fe549-29f3-48b1-b75d-b95fd39d6d2e.png)

fixed in 1.1.3

**Comment by ravingdragoon** [comment]
Seems to be fixed on my end! Thank you!
