### ISSUE TITLE
[BUG] [ChatMessage.speaker.token]: must be a valid 16-character alphanumeric ID

### ISSUE THREAD

**Issue by IrishWolf** [hktrpg/foundryVTT-speak-as#12]
Foundry-Version: 10.290
Reproducable without any other modules.

If you choose an character you're not assigned to, the following errors are thrown.
Independently if you have the corresponding token on scene, selected or not.

![image](https://user-images.githubusercontent.com/36819852/235596742-027cb5dd-4004-4385-b733-ba02d019cc7f.png)

![image](https://user-images.githubusercontent.com/36819852/235596871-114da6a4-64e4-4888-a9cc-0e2216c6ccf8.png)

**Comment by zeteticl** [comment]
Fixed on v1.4.0
