### ISSUE TITLE
Bug Report - Visual Legibility issues

### ISSUE THREAD

**Issue by nandezzy** [hktrpg/foundryVTT-speak-as#2]
![Screen Shot 2021-09-02 at 3 30 19 PM](https://user-images.githubusercontent.com/90004589/131906255-44edbcbf-0e3a-41e8-af5f-eb5d09f9e99d.png)

This seems to be working correctly, though I'm not sure what the second check box is for. In either case, it disappears on the dark background behind my map. I have several other modules affecting this area, so it may require some troubleshooting to fix.

**Comment by zeteticl** [comment]
which version speak as are using?
and what modules does affecting this area?

**Comment by Buzzworth** [comment]
I am having the same issue after updating. It appears to be an issue with the plutonium module and only appears when plutonium is enabled.

It also seems to break with the PopOut! module.

**Comment by zeteticl** [comment]
> plutonium



> I am having the same issue after updating. It appears to be an issue with the plutonium module and only appears when plutonium is enabled.
> 
> It also seems to break with the PopOut! module.


what is plutonium module? I cant find it.
what mean break with PopOut! ? i am work fine with it.

**Comment by nandezzy** [comment]
> which version speak as are using?
> and what modules does affecting this area?

I have quite a few modules that affect chat. I just updated to the latest and it's better, but still a bit funky (tight spaced to the module below it)

Short list...

Chat Portrait
Chat Scrolling
Damage Log
DF Chat Enhancements
Dice Tray
Polyglot

I think that's all of them

![Screen Shot 2021-09-03 at 2 05 16 PM](https://user-images.githubusercontent.com/90004589/132048678-01a94e9d-791e-4234-9e3a-cacb236b8688.png)

**Comment by zeteticl** [comment]
v1.1.5 FIXED 
i hope
