### ISSUE TITLE
Module Incompatibility: DF Chat Enhancements

### ISSUE THREAD

**Issue by deraviin** [hktrpg/foundryVTT-speak-as#4]
Having Speak As and DF Chat Enhancements on at the same time causes a visual glitch where DFCE's buttons are doubled. The buttons on top change color when clicked but are otherwise non functional.
![0e3e5ac20abdf4739a82faa5cb0ea7a3](https://user-images.githubusercontent.com/46595619/132935567-cec72b03-e90a-43fa-bb79-e0d75e2d3e71.png)

**Comment by zeteticl** [comment]
![image](https://user-images.githubusercontent.com/23254376/132937786-4873ea4d-618d-44cd-b0bf-67186c7fd5df.png)

Work fine with me
Speak as 1.1.5
DFCE 3.3.0
