### ISSUE TITLE
show speaker-identity with rolls

### ISSUE THREAD

**Issue by IrishWolf** [hktrpg/foundryVTT-speak-as#6]
Firs of all: I like this package very much!

But is it possible to overwrite rolls as well?
At this point it looks like this for me:

![image](https://user-images.githubusercontent.com/36819852/149667165-19651c03-8005-469c-a171-f5a72694e144.png)

If I postIt would be lovely if the /r [xdy] would get the charackter-name, too.

**Comment by zeteticl** [comment]
I don't think it will work for now, I re-read the documentation and tests last night and still can't find the hack about rolling dice. 
So maybe this behavior is not supported unless there is an update on FVTT.

**Comment by IrishWolf** [comment]
Okay, thats a pity but big thanks for trying and the fast reply :)

**Comment by zeteticl** [comment]
I have some idea about this behavior.
Maybe there are other way to achieve, if i rewrite the mod.
But i am working on other project.
So maybe i will try it in a month or two.

**Comment by zeteticl** [comment]
Other dev's response
![image](https://user-images.githubusercontent.com/23254376/149751784-260ee982-9b66-40d7-b740-b69d7c9d0f9c.png)

**Comment by IrishWolf** [comment]
Thx again!
Then let's hope they fix it^^

**Comment by zeteticl** [comment]
![image](https://user-images.githubusercontent.com/23254376/156877272-fbc84cb5-d018-41fa-a0e8-b2f12e8fe1fa.png)

latest FVTT seen fix the bug.
So close this issue
