### ISSUE TITLE
[error] Invalid language definition in Package speak-as: Language JSON path languages/en.json does not exist

### ISSUE THREAD

**Issue by zach-at-healthpilot** [hktrpg/foundryVTT-speak-as#7]
getting the above error on run:
`[error] Invalid language definition in Package speak-as: Language JSON path languages/en.json does not exist`
node 14.8.0
foundry 9.25x
mac os 10
speak-as : latest

**Comment by zeteticl** [comment]
fix by 1.2.2 
Thankyou for report
