### ISSUE TITLE
Update to Foundryv10

### ISSUE THREAD

**Issue by IrishWolf** [hktrpg/foundryVTT-speak-as#8]
With Foundryv10 this module seems to have problems.
If you try to speak as someone without an token on the scene you get the follwoing errors:

![image](https://user-images.githubusercontent.com/36819852/199840332-794bf63f-f7f6-4828-a7aa-f95f3ef9c35e.png)

![image](https://user-images.githubusercontent.com/36819852/199840410-4e07bd64-3c45-44a1-bf6c-ab8557f160d2.png)

![image](https://user-images.githubusercontent.com/36819852/199840454-f5e7133d-bf50-4800-a8d0-bb33a97d04c1.png)

I really love this module and would be happy if it could be updated.

**Comment by zeteticl** [comment]
updated
