### ISSUE TITLE
Remove V10 warnings

### ISSUE THREAD

**Issue by farling42** [hktrpg/foundryVTT-speak-as#9]
module.json is generating 3 warnings whenever Foundry goes to the setup screen.

The required changes are:
- remove the empty array definitions, they are not needed at all and only create warnings in V10 (esmodules, styles, packs, system, dependencies)
- Add an "id" line after the "name" line, with the same value as the "name" line.

**Comment by zeteticl** [comment]
Thank you for information.
updated to v1.3.1!
